"""
Renaming
"""

renames = {
    "Antigua-and-barbuda": "Antigua and Barbuda",
    "Bosnia-and-herzegovina": "Bosnia and Herzegovina",
    "Burkina-faso": "Burkina Faso",
    "Cape-verde": "Cape Verde",
    "Central-african-republic": "Central African Republic",
    "Congo-(dem.-rep.)": "DR Congo",
    "Costa-rica": "Costa Rica",
    "Cote-d'ivoire-(ivory-coast)": "Ivory Coast",
    "Cote-d&#39;ivoire-(ivory-coast)": "Ivory Coast",
    "Czech-republic": "Czech Republic",
    "Dominican-republic": "Dominican Republic",
    "El-salvador": "El Salvador",
    "Equatorial-guinea": "Equatorial Guinea",
    "Eswatini": "Swaziland",
    "Guinea-bissau": "Guinea-Bissau",
    "Hong-kong": "Hong Kong",
    "Marshall-islands": "Marshall Islands",
    "New-zealand": "New Zealand",
    "North-korea": "North Korea",
    "North-macedonia": "North Macedonia",
    "Palestinian-territories": "Palestine",
    "Papua-new-guinea": "Papua New Guinea",
    "Russian-federation": "Russia",
    "Saint-kitts-and-nevis": "Saint Kitts and Nevis",
    "Saint-lucia": "Saint Lucia",
    "San-marino": "San Marino",
    "Sao-tome-and-principe": "Sao Tome and Principe",
    "Saudi-arabia": "Saudi Arabia",
    "Sierra-leone": "Sierra Leone",
    "Solomon-islands": "Solomon Islands",
    "South-africa": "South Africa",
    "South-korea": "South Korea",
    "South-sudan": "South Sudan",
    "Sri-lanka": "Sri Lanka",
    "St.-vincent-and-the-grenadines": "Saint Vincent and the Grenadines",
    "Timor-leste": "Timor-Leste",
    "Trinidad-and-tobago": "Trinidad and Tobago",
    "T%c3%bcrkiye": "Turkey",
    "United-arab-emirates": "United Arab Emirates",
    "United-kingdom": "United Kingdom",
    "United-states-of-america": "United States",
    "Vatican-city": "Vatican City",
    "Viet-nam": "Vietnam",
}
